server:
  port: 8081
  error:
    whitelabel:
      enabled: false
    include-message: always
spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
  flyway:
    baseline-on-migrate: true
  data:
    web:
      pageable:
        max-page-size: 50
my:
  name: egor
